Implement workaround for missing git push
Let's fall back to "apt-get source" for a specific package for now. One
has to make sure proper apt sources make it possible to "apt-get source"
this specific package's version.

Note: commit best viewed with "-x -w" due to indentation changes.


git-svn-id: svn+ssh://svn.debian.org/svn/d-i/trunk@70211 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/l10n/calc-release-status b/scripts/l10n/calc-release-status
--- a/scripts/l10n/calc-release-status
+++ b/scripts/l10n/calc-release-status
@@ -173,10 +173,15 @@ for p_dir in `real_contents packages_list | sort `; do
 	if [ ! -d $package/$version/po ]; then
 		mkdir -p $package/$version
 		pushd $package/$version >/dev/null
-		git clone $GITREPO/$package
-		pushd $package
-		git checkout -b tag $version || { echo "Unable to find $version in $package"; exit 1; }
-		popd
+		if [ "$package" != "yaboot-installer" ]; then
+			git clone $GITREPO/$package
+			pushd $package
+			git checkout -b tag $version || { echo "Unable to find $version in $package"; exit 1; }
+			popd
+		else
+			apt-get source $package=$version
+			mv $package-*/ $package
+		fi
 		cp -r $package/debian/po .
 	else
 		pushd $package/$version >/dev/null
