calc-release-status: Fix tag lookup in git.
Fix a couple of things at once:
 - Strip the epoch if there's one.
 - Don't try to track tags (remove "-t" from "git checkout").
 - Fail if a tag checkout fails, so that it can be investigated
   (e.g. missing push for the said tag).

git-svn-id: svn+ssh://svn.debian.org/svn/d-i/trunk@68976 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/scripts/l10n/calc-release-status b/scripts/l10n/calc-release-status
--- a/scripts/l10n/calc-release-status
+++ b/scripts/l10n/calc-release-status
@@ -169,12 +169,14 @@ for p_dir in `real_contents packages_list | sort `; do
 
 	log "- processing $p_dir ($version)"
 	echo "$package ($version)" >>packages.log
+	# Assume tags with an epoch are committed without it ("bar" instead of "foo:bar"):
+	version=$(echo $version|sed 's/^[0-9]\+://')
 	if [ ! -d $package/$version/po ]; then
 		mkdir -p $package/$version
 		pushd $package/$version >/dev/null
 		git clone $GITREPO/$package
 		pushd $package
-		git checkout -b tag -t $version >/dev/null || true
+		git checkout -b tag $version || { echo "Unable to find $version in $package"; exit 1; }
 		popd
 		cp -r $package/debian/po .
 	else
