Make create_xml use original english text for fuzzy entries.
git-svn-id: svn+ssh://svn.debian.org/svn/d-i/trunk@70218 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/manual/scripts/create_xml b/manual/scripts/create_xml
--- a/manual/scripts/create_xml
+++ b/manual/scripts/create_xml
@@ -59,7 +59,19 @@ for ORIGXML in `find $SOURCEDIR -name "*.xml"` ; do
             echo "Error: error $RC while executing msgconv"
             continue
         fi
-        po2xml $ORIGXML /tmp/tmp.po.$$ > $XML
+        msgattrib \
+            --translated \
+            --no-fuzzy \
+            --output-file="/tmp/tmp.po2.$$" \
+            "/tmp/tmp.po.$$" \
+        ;
+        RC=$?
+        if [ $RC -ne 0 ] ; then
+            RET=$RC
+            echo "Error: error $RC while executing msgattrib"
+            continue
+        fi
+        po2xml $ORIGXML /tmp/tmp.po2.$$ > $XML
         RC=$?
         if [ $RC -ne 0 ] ; then
             RET=$RC
