Check that the required tools are there before continuing
git-svn-id: svn+ssh://svn.debian.org/svn/d-i/trunk@68617 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/manual/scripts/create_xml b/manual/scripts/create_xml
--- a/manual/scripts/create_xml
+++ b/manual/scripts/create_xml
@@ -10,6 +10,15 @@ fi
 
 language=${1:-pl}
 
+# Required tools
+for tool in msgconv po2xml ; do
+    if [ -z "`which $tool`" ] ; then
+        echo "ERROR: $tool is required, please install it."
+        exit 1
+    fi
+done
+
+
 BUILDDIR="./build"
 if [ -z "$PO_USEBUILD" ] ; then
     WORKDIR="./integrated"
