Check that the required tools are there before continuing
git-svn-id: svn+ssh://svn.debian.org/svn/d-i/trunk@68614 48c42b26-1dd6-0310-b98f-a58d8bce7237

diff --git a/manual/scripts/merge_xml b/manual/scripts/merge_xml
--- a/manual/scripts/merge_xml
+++ b/manual/scripts/merge_xml
@@ -15,6 +15,14 @@ language=${1:-pl}
 SCRIPTDIR="./scripts"
 BUILDDIR="./build"
 
+# Required tools
+for tool in gawk egrep iconf ; do
+    if [ -z "`which $tool`" ] ; then
+        echo "ERROR: $tool is required, please install it."
+        exit 1
+    fi
+done
+
 LANGDIR="./$language"
 [ -d $LANGDIR ] || exit 1
 
